project:
  type: website
  output-dir: docs

website:
  title: "PA446 Presentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: sandstone
    mainfont: Arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: "Courier New"
    css: styles.css
    toc: true

editor: visual

